### PR TITLE
ML-DSA signing keys

### LINKED ISSUE #2577: Can't seem to load ML-DSA private key with rustls-post-quantum 0.2.3
**Checklist**
* [X] I've searched the issue tracker for similar bugs.

**Describe the bug**
Hi! Many thanks for adding PQC DSA beyond the PQC KEM support that rustls-post-quantum already accomplished, both much appreciated and I understand that this new addition came clearly labeled "add _unstable_ ML-DSA support" but I can't seem to get it to load any ML-DSA private key despite trying:

- mine generated with OpenSSL 3.5.1 (which has native ML-DSA support since 3.5.0)
- mine generated on another computer with OpenSSL 3.4.1 and oqsprovider 0.9.0
- the one corresponding to the test certificate linked [in the PR thread](https://github.com/rustls/webpki/pull/348#issuecomment-2984029964)

The error I am stuck at is "failed to parse private key as RSA, ECDSA, or EdDSA" which exists in 4 different places in rusts 0.23.29 source but I managed to track it down specifically to [aws_lc_rs/sign.rs#L36](https://github.com/rustls/rustls/blob/v/0.23.29/rustls/src/crypto/aws_lc_rs/sign.rs#L36) which is all about RSA, ECDSA and EdDSA indeed... If I understand its Cargo.toml correctly, rustls-post-quantum (with "aws-lc-rs-unstable" feature enabled) is not at all a fork of rustls (and "aws-lc-rs" feature) but the former actually depend on the latest stable release of the latter, but is it normal that loading my PQC creds happens in the non-PQC part? 🙂 

I mean, it is entirely possible that I misunderstood the "Experimental support for ML-DSA signature schemes is now available via rustls-post-quantum 0.2.3" announcement: perhaps for now the support is only for validating a certificate presented by a remote peer as opposed to loading your own ML-DSA files like I am trying to do?

**To Reproduce**
I guess the best way would be to try to add Mutual TLS support in the existing rustls-post-quantum/examples/client.rs or to implement a corresponding "server.rs" but what I have been trying so far is simply with rocket.rs (from main branch, not the latest 0.5.1 release which still tries to parse keys by itself even if the crypto provider is overridden) with the very first instruction being `rustls_post_quantum::provider().install_default().unwrap();` as per rustls documentation or `let _ = rustls_post_quantum::provider().install_default();` as inferred from rocket documentation.

PS: if like me you/someone tries to patch rustls to help figure out what is going on in rustls-post-quantum, beware that unpatched rustls can still be brought in by rocket and tokio-rustls for example.

**Applicable Version(s)**
rustls-post-quantum 0.2.3
rustls 0.23.29
https://github.com/rwf2/Rocket/tree/master since May the 4th

**Expected behavior**
Same as always with TLS the only difference being credentials of the ML-DSA type instead of RSA, ECDSA or EdDSA. Further explained in the "Load/validate and parse Quantum certificates generated by oqsprovider" issue #2417 with now the addition of files generated by OpenSSL>=3.5.0 itself.

**Additional context**
Having edited rustls-post-quantum/src/lib.rs I am quite confident that I successfully forced rocket to use rustls-post-quantum instead of any other crypto provider, but private key parsing still seems to go from rustls-post-quantum into non-PQC rustls code; maybe more ML-DSA patches are needed in rustls and/or rustls-pemfile?

### PR DESCRIPTION
**Pull request by djc**
Fixes #2577.

## Proposed release notes

* Support using ML-DSA keys for signing when the `aws-lc-rs-unstable` feature is enabled.

### CODE REVIEW

File: rustls/src/crypto/signer.rs [hunk 1]
```diff
@@ -243,8 +243,8 @@ impl CertifiedKey {
     }
 }
 
-#[cfg_attr(not(any(feature = "aws-lc-rs", feature = "ring")), allow(dead_code))]
-pub(crate) fn public_key_to_spki(
+/// Convert a public key and algorithm identifier into a SubjectPublicKeyInfo.
```
Comment (ctz) [inline rustls/src/crypto/signer.rs]:
```suggestion
/// Convert a public key and algorithm identifier into a `SubjectPublicKeyInfo`.
///
/// In the returned encoding, `alg_id` is used as the `algorithm` field, and `public_key`
/// is wrapped inside an ASN.1 `BIT STRING` and then used as the `subjectPublicKey`
/// field.
```

File: rustls-post-quantum/src/lib.rs [hunk 2]
```diff
@@ -25,10 +25,184 @@ pub fn provider() -> CryptoProvider {
...
     {
         provider.signature_verification_algorithms = SUPPORTED_SIG_ALGS;
+        provider.key_provider = &key_provider::PqAwsLcRs;
     }
     provider
 }
 
+#[cfg(feature = "aws-lc-rs-unstable")]
+mod key_provider {
+    #[cfg(feature = "aws-lc-rs-unstable")]
```
Comment (cpu) [inline rustls-post-quantum/src/lib.rs]: If the entire `mod` is behind a `cfg(feature = "aws-lc-rs-unstable")` do these handful of imports need their own duplicated `cfg` guard?

File: rustls-post-quantum/src/lib.rs [hunk 3]
```diff
@@ -25,10 +25,184 @@ pub fn provider() -> CryptoProvider {
...
+
+            for &alg in ML_DSA_SIGNING_ALGS {
+                let key_pair = match &key_der {
+                    PrivateKeyDer::Pkcs8(pkcs8) => {
+                        match PqdsaKeyPair::from_pkcs8(alg, pkcs8.secret_pkcs8_der()) {
+                            Ok(key_pair) => key_pair,
+                            Err(_) => continue,
+                        }
+                    }
+                    // To do: support `PqdsaKeyPair::from_raw_private_key()`?
```
Comment (cpu) [inline rustls-post-quantum/src/lib.rs]: Can you write this "TODO:"? I think that form is most common vs "to do" and some IDEs will pick up as a special annotation.

File: rustls-post-quantum/src/lib.rs [hunk 4]
```diff
@@ -25,10 +25,184 @@ pub fn provider() -> CryptoProvider {
...
+
+            Some(Box::new(PqdsaSigner {
+                key: self.inner.clone(),
+                kind: self.kind,
+            }))
+        }
+
+        fn public_key(&self) -> Option<SubjectPublicKeyInfoDer<'_>> {
+            Some(public_key_to_spki(
+                self.kind.alg_id(),
```
Comment (cpu) [inline rustls-post-quantum/src/lib.rs]: This will want to be `&self.kind.alg_id()` once you take rustls 0.23.31 and add the import for `public_key_to_spki()`.

File: rustls-post-quantum/src/lib.rs [hunk 5]
```diff
@@ -25,10 +25,184 @@ pub fn provider() -> CryptoProvider {
...
+                return Ok(Arc::new(PqdsaSigningKey {
+                    kind: if alg == &ML_DSA_44_SIGNING {
+                        PqdsaKeyKind::MlDsa44
+                    } else if alg == &ML_DSA_65_SIGNING {
+                        PqdsaKeyKind::MlDsa65
+                    } else if alg == &ML_DSA_87_SIGNING {
+                        PqdsaKeyKind::MlDsa87
+                    } else {
+                        unreachable!("unexpected ML-DSA signing algorithm")
+                    },
```
Comment (cpu) [inline rustls-post-quantum/src/lib.rs]: I think this can be made nicer if you flip things around so that `ML_DSA_SIGNING_ALGS` is a slice of `PqdsaKeyKind`, and then have a `impl From<PqdsaKeyKind> for &PqdsaSigningAlgorithm` to use on L66. It avoids this `unreachable!()` and moves this conversion logic closer to the enum where I think it fits better.

Something like this: https://github.com/rustls/rustls/commit/b231c9e69ead1ad478919b96b25b0d9dc7993891

File: rustls-post-quantum/src/lib.rs [hunk 6]
```diff
@@ -25,10 +25,184 @@ pub fn provider() -> CryptoProvider {
...
+                }));
+            }
+
+            if let Ok(key) = sign::any_supported_type(&key_der) {
+                return Ok(key);
+            }
+
+            Err(Error::General(
+                "failed to parse private key as ML-DSA, RSA, ECDSA, or EdDSA".into(),
+            ))
```
Comment (cpu) [inline rustls-post-quantum/src/lib.rs]: nit: would a `match` be more idiomatic here?

```rust
            match sign::any_supported_type(&key_der) {
                Ok(key) => Ok(key),
                Err(_) => Err(Error::General(
                    "failed to parse private key as ML-DSA, RSA, ECDSA, or EdDSA".into(),
                )),
            }
```

File: rustls-post-quantum/src/lib.rs [hunk 7]
```diff
@@ -25,10 +25,184 @@ pub fn provider() -> CryptoProvider {
...
+
+    struct PqdsaSigningKey {
+        kind: PqdsaKeyKind,
+        inner: Arc<PqdsaKeyPair>,
+    }
+
+    impl SigningKey for PqdsaSigningKey {
+        fn choose_scheme(&self, offered: &[SignatureScheme]) -> Option<Box<dyn Signer>> {
+            let scheme = self.kind.scheme();
+            if !offered.contains(&scheme) {
```
Comment (cpu) [inline rustls-post-quantum/src/lib.rs]: nit: inline `scheme`?

File: rustls-post-quantum/src/lib.rs [hunk 8]
```diff
@@ -25,10 +25,184 @@ pub fn provider() -> CryptoProvider {
...
+
+        fn public_key(&self) -> Option<SubjectPublicKeyInfoDer<'_>> {
+            Some(public_key_to_spki(
+                self.kind.alg_id(),
+                self.inner.public_key(),
+            ))
+        }
+
+        fn algorithm(&self) -> SignatureAlgorithm {
+            SignatureAlgorithm::Unknown(255)
```
Comment (cpu) [inline rustls-post-quantum/src/lib.rs:112]: Is there something to cite for the use of `255` here?

File: rustls-post-quantum/src/lib.rs [hunk 9]
```diff
@@ -25,10 +25,184 @@ pub fn provider() -> CryptoProvider {
...
+
+    impl Debug for PqdsaSigner {
+        fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
+            f.debug_struct("PqdsaSigner")
+                .field("scheme", &self.kind.scheme())
+                .finish_non_exhaustive()
+        }
+    }
+
+    #[cfg(feature = "aws-lc-rs-unstable")]
```
Comment (cpu) [inline rustls-post-quantum/src/lib.rs]: this `cfg` can fall away because it's inside the `mod` too, like the import ones.

**Review by cpu — COMMENTED** [review]
FWIW I got this branch building locally to fiddle with review feedback using this small patch: https://github.com/rustls/rustls/commit/7ae2f2b63434bc73f1a70431b236d79f323cea78

What kind of test coverage did you have in-mind for this to be ready to go? There's some low-level ML-DSA test vectors recently added to Wycheproof (https://github.com/C2SP/wycheproof/pull/146) but I'm not sure how well they'll map into this context.

**Comment by djc** [comment]
I was thinking we could do a handshake with a freshly generated key? I guess that would require rcgen support maybe.

File: rustls-post-quantum/src/lib.rs (hunk 2 above)
Comment (djc) [reply rustls-post-quantum/src/lib.rs]: They don't, cleaned it up.

File: rustls-post-quantum/src/lib.rs (hunk 3 above)
Comment (djc) [reply rustls-post-quantum/src/lib.rs]: Done.

File: rustls-post-quantum/src/lib.rs (hunk 4 above)
Comment (djc) [reply rustls-post-quantum/src/lib.rs]: Fixed.

File: rustls-post-quantum/src/lib.rs (hunk 5 above)
Comment (djc) [reply rustls-post-quantum/src/lib.rs]: Ahh, good idea!

File: rustls-post-quantum/src/lib.rs (hunk 6 above)
Comment (djc) [reply rustls-post-quantum/src/lib.rs]: Yup.

File: rustls-post-quantum/src/lib.rs (hunk 7 above)
Comment (djc) [reply rustls-post-quantum/src/lib.rs]: Done.

File: rustls-post-quantum/src/lib.rs (hunk 8 above)
Comment (djc) [reply rustls-post-quantum/src/lib.rs:112]: Added some comments.

File: rustls-post-quantum/src/lib.rs (hunk 9 above)
Comment (djc) [reply rustls-post-quantum/src/lib.rs]: Done.

File: rustls/src/crypto/signer.rs (hunk 1 above)
Comment (djc) [reply rustls/src/crypto/signer.rs]: This is now #2662.

File: rustls-post-quantum/src/lib.rs [hunk 10]
```diff
@@ -25,10 +25,181 @@ pub fn provider() -> CryptoProvider {
...
+                            Err(_) => continue,
+                        }
+                    }
+                    // TODO: support `PqdsaKeyPair::from_raw_private_key()`?
+                    _ => {
+                        return Err(Error::General(
+                            "ML-DSA keys must be provided in PKCS#8 format".into(),
+                        ));
+                    }
+                };
```
Comment (ctz) [inline rustls-post-quantum/src/lib.rs]: AIUI this will early-reject (eg) a PKCS#1 RSA key. Maybe we should do the `sign::any_supported_type` thing first?

File: rustls-post-quantum/src/lib.rs [hunk 11]
```diff
@@ -25,10 +25,181 @@ pub fn provider() -> CryptoProvider {
...
+
+                return Ok(Arc::new(PqdsaSigningKey {
+                    kind,
+                    inner: Arc::new(key_pair),
+                }));
+            }
+
+            match sign::any_supported_type(&key_der) {
```
Comment (ctz) [inline rustls-post-quantum/src/lib.rs:72]: It might be clearer to dispatch to `rustls::crypto::aws_lc_rs::default_provider().key_provider` here?

File: rustls-post-quantum/src/lib.rs [hunk 12]
```diff
@@ -25,10 +25,181 @@ pub fn provider() -> CryptoProvider {
...
+            match self {
+                Self::MlDsa44 => alg_id::ML_DSA_44,
+                Self::MlDsa65 => alg_id::ML_DSA_65,
+                Self::MlDsa87 => alg_id::ML_DSA_87,
+            }
+        }
+    }
+}
+
 /// Keep in sync with the `SUPPORTED_SIG_ALGS` in `rustls::crypto::aws_lc_rs`.
```
Comment (ctz) [inline rustls-post-quantum/src/lib.rs:196]: Missing the recent additions to the `SignatureScheme::ECDSA_NISTP521_SHA512` mapping.

File: rustls-post-quantum/src/lib.rs (hunk 11 above)
Comment (ctz) [reply rustls-post-quantum/src/lib.rs:72]: (Probably not, actually.)

File: rustls-post-quantum/src/lib.rs (hunk 10 above)
Comment (djc) [reply rustls-post-quantum/src/lib.rs]: Ah, good catch -- and I think it would also have failed with non-ML-DSA PKCS#8 keys. Restructured.

File: rustls-post-quantum/src/lib.rs (hunk 12 above)
Comment (djc) [reply rustls-post-quantum/src/lib.rs:196]: Ah, added those.

File: rustls-post-quantum/src/lib.rs [hunk 13]
```diff
@@ -280,3 +280,109 @@ static SUPPORTED_SIG_ALGS: WebPkiSupportedAlgorithms = WebPkiSupportedAlgorithms
...
+        CertificateParams, CertifiedIssuer, ExtendedKeyUsagePurpose, IsCa, KeyPair, KeyUsagePurpose,
+    };
+    use rustls::pki_types::PrivateKeyDer;
+    use rustls::{
+        ClientConfig, ClientConnection, ConnectionCommon, RootCertStore, ServerConfig,
+        ServerConnection, SideData,
+    };
+
+    #[test]
+    fn ml_kem() {
```
Comment (ctz) [inline rustls-post-quantum/src/lib.rs]:
```suggestion
    fn ml_dsa() {
```

**Comment by djc** [comment]
* Published rustls-post-quantum v0.2.4 at registry `crates-io`
* [new tag]           rustls-post-quantum-v/0.2.4 -> rustls-post-quantum-v/0.2.4
* [Release notes](https://github.com/rustls/rustls/releases/tag/rustls-post-quantum-v%2F0.2.4)
