### PR TITLE
Lower noise in ci-bench

### LINKED ISSUE #1494: CI benchmarks: use cachegrind "client requests" for more precise instruction counts
From [this article](https://kobzol.github.io/rust/rustc/2023/09/23/rustc-runtime-benchmarks.html):

> Valgrind has support for [client requests](https://valgrind.org/docs/manual/manual-core-adv.html#manual-core-adv.clientreq), which allow the profiled program (amongst other things) to selectively enable and disable instrumentation for parts of the program.

They are not yet available for cachegrind, but it looks like support is coming in the next release. Using client requests would greatly improve our benchmarking harness, making it possible to ignore setup code when counting instructions. The functionality should be accessible through the [crabgrind](https://github.com/2dav/crabgrind) crate.

The current workaround to discard the instruction counts originating from setup code is to run the setup code in isolation and subtract the measured icount from the full benchmark's icount. This works well enough in practice, but gets confusing when you are investigating a regression, because the cachegrind diff does include the benchmark's setup code.

### PR DESCRIPTION
**Pull request by ctz**
For me this reduces maximum run-to-run noise to 0.29%, from about 0.61% on main.

There will be a discontinuity in benchmark numbers in this PR, as we're reducing the scope of what is measured.

fixes #1494

### CODE REVIEW

File: ci-bench/src/cachegrind.rs [hunk 1]
```diff
@@ -291,3 +291,24 @@ pub fn diff(baseline: &Path, candidate: &Path, scenario: &str) -> anyhow::Result
 
     Ok(diff)
 }
+
+pub(crate) fn pause_instruction_count() -> PauseGuard {
+    PauseGuard::new()
+}
+
+pub(crate) struct PauseGuard;
```
Comment (cpu) [inline ci-bench/src/cachegrind.rs:304]: Maybe worth an internal rustdoc comment to warn this won't do the right thing (AFAICT) if you end up creating multiple `PauseGuard`'s and drop one but not the other. I think the first that gets dropped would toggle collection off and the next drop would turn it back on?

Probably not a concern for real usage :shrug:

File: ci-bench/src/main.rs [hunk 2]
```diff
@@ -384,6 +384,23 @@ fn aws_lc_rs_ticketer() -> Arc<dyn rustls::server::ProducesTickets> {
...
+        ..base
+    }
+}
+
+#[derive(Debug)]
+struct NotRandom;
+
+impl rustls::crypto::SecureRandom for NotRandom {
+    fn fill(&self, buf: &mut [u8]) -> Result<(), rustls::crypto::GetRandomFailed> {
+        buf.fill(0x5a);
```
Comment (cpu) [inline ci-bench/src/main.rs:399]: oblig. https://xkcd.com/221/ :game_die: :laughing:

**Review by cpu — COMMENTED** [review]
Nice!

**Review by djc — APPROVED** [review]

File: ci-bench/src/cachegrind.rs [hunk 3]
```diff
@@ -291,3 +291,29 @@ pub fn diff(baseline: &Path, candidate: &Path, scenario: &str) -> anyhow::Result
 
     Ok(diff)
 }
+
+pub(crate) fn reset_instruction_count() {
+    #[cfg(target_os = "linux")]
+    crabgrind::callgrind::zero_stats();
```
Comment (ctz) [inline ci-bench/src/cachegrind.rs:297]: sadly this actually does jack, because we're running this under _cachegrind_ and not _callgrind_  -- the version of valgrind we have in ci does not have a programmatic control interface for cachegrind (though does in later versions)

will have a look to see if we can use callgrind instead (we turn off the cache simulation, so they are should be very similar)

Comment (djc) [reply ci-bench/src/cachegrind.rs:297]: Can we upgrade our version of valgrind?

Comment (ctz) [reply ci-bench/src/cachegrind.rs:297]: Unfortunately the test runner is on debian stable, installing a newer valgrind from debian unstable would work, but would give us an odd mix of the two. I think if I get into changing the ansible scripts for this, I would rather spend the time installing docker to make it easier to (eg) rev the rust compiler too.

Comment (cpu) [reply ci-bench/src/cachegrind.rs:297]: Will benchmarking from Docker introduce any significant overhead?

Comment (ctz) [reply ci-bench/src/cachegrind.rs:297]: I think some networking/filesystem performance can be worse, but pure CPU should be identical.

Comment (ctz) [reply ci-bench/src/cachegrind.rs]: callgrind seems to work well now, though renaming a bunch of types/files called CachegrindSomething remains to do.

File: ci-bench/src/main.rs [hunk 4]
```diff
@@ -384,6 +384,23 @@ fn aws_lc_rs_ticketer() -> Arc<dyn rustls::server::ProducesTickets> {
     aws_lc_rs::Ticketer::new().unwrap()
 }
 
+fn derandomize(base: rustls::crypto::CryptoProvider) -> rustls::crypto::CryptoProvider {
```
Comment (cpu) [inline ci-bench/src/main.rs:387]: nit: I think the `derandomize` signature is still using the fully qualified `CryptoProvider` type even though it's now imported in-scope.

File: ci-bench/src/cachegrind.rs [hunk 5]
```diff
@@ -233,61 +233,55 @@ impl Sub for InstructionCounts {
...
-        .arg("--mod-funcname=s/17h[0-9a-f]+E\\.llvm\\.\\d+/E/")
+    // callgrind_annotate formats the callgrind output file, suitable for comparison with
+    // callgrind_differ
+    let callgrind_annotate_base = Command::new("callgrind_annotate")
         .arg(
             baseline
                 .join(CACHEGRIND_OUTPUT_SUBDIR)
                 .join(scenario),
         )
+        .arg("--auto=no")
```
Comment (cpu) [inline ci-bench/src/cachegrind.rs]: Maybe worth a comment here indicating why we want to turn off automatic annotation of source files that contributed to the event count threshold?

**Review by cpu — APPROVED** [review]
:racehorse:

File: ci-bench/src/cachegrind.rs [hunk 6]
```diff
@@ -233,61 +233,55 @@ impl Sub for InstructionCounts {
...
-    let diff =
-        String::from_utf8(cg_annotate.stdout).context("cg_annotate produced invalid UTF8")?;
+    let string_base = String::from_utf8(callgrind_annotate_base.stdout)
+        .context("callgrind_annotate produced invalid UTF8")?;
+    let string_candidate = String::from_utf8(callgrind_annotate_candidate.stdout)
+        .context("callgrind_annotate produced invalid UTF8")?;
 
-    fs::remove_file(tmp_path).ok();
+    // TODO: reinstate actual diffing, using `callgrind_differ` crate
+    let diff =
```
Comment (djc) [inline ci-bench/src/cachegrind.rs]: Nit: inline the `diff` binding?

File: ci-bench/src/benchmark.rs [hunk 7]
```diff
@@ -27,40 +26,13 @@ pub fn validate_benchmarks(benchmarks: &[Benchmark]) -> anyhow::Result<()> {
...
-    }
-
     Ok(())
 }
 
 /// Specifies how the results of a particular benchmark should be reported
 pub enum ReportingMode {
     /// All instructions are reported
     AllInstructions,
-    /// All instructions are reported, after subtracting the instructions of the setup code
```
Comment (djc) [inline ci-bench/src/benchmark.rs:59]: Is the enum still useful?

File: ci-bench/README.md [hunk 8]
```diff
@@ -2,7 +2,7 @@
 
 This crate is meant for CI benchmarking. It has two modes of operation:
 
-1. Measure CPU instructions using `cachegrind`.
+1. Measure CPU instructions using `callgrind`.
```
Comment (djc) [inline ci-bench/README.md:5]: Should all of this be in the previous commit that actually switched?

**Review by djc — APPROVED** [review]
Nice!

File: ci-bench/src/benchmark.rs (hunk 7 above)
Comment (ctz) [reply ci-bench/src/benchmark.rs:59]: removed and squashed removal into the original commit
