### PR TITLE
Ticket generations

### LINKED ISSUE #2778: The test of TicketRotator maybe not correct
When test "ticketrotator_remains_usable_over_temporary_ticketer_creation_failure", the origin code use a `fail_generator` and set the time to `now + 10s` to  simulate the situation where the rotation fail. But, when `encrpt` or `decrypt` later, it will still use `UnixTime::now()` and obviously it's not yet time for rotation, so the test will always pass.

So, was the original design that **even if the rotation failed, the previous generator would still be used?**

https://github.com/rustls/rustls/blob/ad3c1c6ed86638f8376728c78ac3f61e4340675f/rustls/src/ticketer.rs#L181-L212

`encrypt` will `UnixTime::now()`:
https://github.com/rustls/rustls/blob/ad3c1c6ed86638f8376728c78ac3f61e4340675f/rustls/src/ticketer.rs#L112-L113

`decrypt` will `UnixTime::now()`:
https://github.com/rustls/rustls/blob/ad3c1c6ed86638f8376728c78ac3f61e4340675f/rustls/src/ticketer.rs#L118-L119

### PR DESCRIPTION
**Pull request by djc**
Fixes #2778.

cc @BamLubi I hope this addresses your concerns!

### CODE REVIEW

File: rustls/src/ticketer.rs [hunk 1]
```diff
@@ -39,38 +39,62 @@ impl TicketRotator {
...
+                return Some(plain);
+            }
+        }
+
+        // If we don't have a previous ticketer, we can't decrypt.
+        let Some(prev) = &state.previous else {
+            return None;
+        };
+
+        // If the previous ticketer is more than one `lifetime` old, decline to encrypt.
```
Comment (ctz) [inline rustls/src/ticketer.rs]: Isn't this guaranteed to be true? How do we end up with a `state.previous` otherwise?

s/encrypt/decrypt/ in comment

Comment (djc) [reply rustls/src/ticketer.rs]: Here's a timeline:

- t = 0, we generate a ticketer
- t = 1 lifetime, we fail to generate a ticketer, the old ticketer is now `previous` and `current` becomes `None`
- t = 1.5 lifetimes <-- we are here, `previous` is more than one but less than 2 lifetimes old so we still allow encryption with it
- t = 2.0 lifetimes, we stop encrypting tickets

This is more or less copying the new encryption behavior, which may not make sense?

Comment (ctz) [reply rustls/src/ticketer.rs]: Sorry, I misread. That timeline does reflect what I think is a desired behaviour.

**Comment by djc** [comment]
(Fixed the typo.)
