### PR TITLE
Fixes for TLS 1.2 session resumption

### LINKED ISSUE #797: Session resumption in TLS 1.2 violates RFC
In the section of code for session resumption in TLS 1.2, the case where `session_id` has length zero for both `resuming` and `self` is not considered: https://github.com/rustls/rustls/blob/5e9ccd4b5b1154ac4b55316dfad178ba09957069/rustls/src/client/tls12.rs#L114-L115

According to the [TLS 1.2 RFC](https://datatracker.ietf.org/doc/html/rfc5246)

> The server may return an empty session_id to indicate that the session will not be cached and therefore cannot be resumed.

This can cause an error where a peer switches from using TLS 1.3 to TLS 1.2 (which causes a change in the negotiated ciphersuite) which results in a `PeerMisbehavedError` being thrown: https://github.com/rustls/rustls/blob/5e9ccd4b5b1154ac4b55316dfad178ba09957069/rustls/src/client/tls12.rs#L117-L122

I have reproduced the error here: https://github.com/tanyav2/replicate-rustls-bug

This doesn't occur when a TLS 1.2 server is restarted again using TLS 1.2 because when the `rustls-client` sends a certain `session_id` to the server, and the server responds with an empty `session_id`, which are different, and so the session is not resumed.

However, if the client first connects to a server running TLS 1.3, and then the server is restarted with TLS 1.2, the client sends an empty `session_id` because it is expecting to connect to a TLS 1.3 server. But because the server is now TLS 1.2, the empty `session_id` that the server sends in response matches the client's `session_id`, and the client ends up believing that the server is agreeing to resume the session. 

The fix can be something like https://github.com/tanyav2/rustls/blob/d70ee9240209d4acafdaf7cac1f911f9c681e5b5/rustls/src/client/tls12.rs#L113-L114:
```rust
    if (SessionID::empty() != resuming.session_id)
        && (resuming.session_id == self.session_id) 
    {
        debug!("Server agreed to resume");
```

The other thing worth noting is when TLS 1.2 server is restarted, it has an empty `session_id` but it sets the `SessionTicketAck` extension in response to the `SessionTicketOffer` sent by the client during `ClientHello`. However, when the server is downgraded from 1.3 -> 1.2, the client doesn't send a `SessionTicketOffer` or `SessionTicketRequest`, so the server doesn't respond with a `SessionTicketAck`.

### PR DESCRIPTION
**Pull request by djc**
To make testing this easier (and because it seems useful to signal to the client), we add a method to `StoresServerSessions` that allows the implementation to signal whether it's accepting new sessions.

Fixes #797.

### CODE REVIEW

**Comment by briansmith** [comment]
> To make testing this easier (and because it seems useful to signal to the client), we add a method to `StoresServerSessions` that allows the implementation whether it's accepting new sessions.

Seems some words are missing in "allows the implementation whether."

File: rustls/src/client/tls12.rs [hunk 1]
```diff
@@ -111,7 +111,7 @@ mod server_hello {
 
             // See if we're successfully resuming.
             if let Some(ref resuming) = self.resuming_session {
-                if resuming.session_id == self.session_id {
+                if !resuming.session_id.is_empty() && resuming.session_id == self.session_id {
```
Comment (briansmith) [inline rustls/src/client/tls12.rs:114]: I also think this all is hard to understand because there are implicit assumptions here that aren't documented and not documented in the type system.

Here we have `self.resuming_session` as a TLS 1.3 session where we don't store the session ID, so it is empty, but in this TLS 1.2 code we hadn't accounted for that possibility. Ideally, a TLS 1.3 session shouldn't even have a `session_id` that is comparable to a TLS 1.2 session_id. That is, this line above should have been a compile-time error. So I think a better solution would be to change the type of `resuming.session_id` to `Option<SessionID>` or even clearer define a separate type:
```
enum ResumptionSessionID {
    /// We don't store a session ID for TLS 1.3 sessions.
    Tls13,

    /// A non-empty session ID is always stored for TLS 1.2 sessions.
    ///
    /// The value of the session ID is always non-empty.
    Tls12(SessionID)
}
```

Comment (djc) [reply rustls/src/client/tls12.rs:114]: Yes, I spent quite a bit of time yesterday trying to understand what was going on here and there are a number of things that could be improved. Unfortunately yesterday was my last day of work before my two-week vacation so I'm not sure how much time I'll be able to spend on this in the next week or so.

The improvement you suggested sounds good, but I think maybe we should go further? Some things I've come up with so far:

* We could start encoding the protocol version into the session cache key, making it an opaque `&[u8]`.
* We could change the type representation of the `SessionTicket` extension to use a nested enum rather than separate variants, where the nested enum's variants could be more explicit about the representative version.
* We should clarify what the intention is in preparing a `ClientHello` in terms of sending a 1.3 `PreSharedKeyOffer`, a 1.2 `SessionTicket` or both.
* In the client's 1.2 `ExpectFinished` state, it looks dubious to me that we can save the session if either the session ID or the ticket is empty (we only return early if both are).
* It looks like the client's 1.2 code might save an 1.2 session based on a session ID and a (presumably empty?) ticket from what was actually a cached 1.3 session.
* We might move any version-dependent fields from `ClientSessionValue`/`ServerSessionValue` into a version-variant enum, to make it more obvious what's going on there.

Yesterday I was still looking into the second problem @tanyav2 mentioned in #797, about which extensions the client sends in a 1.2-after-cached-1.3 scenario, so I just ran out of time. I dug through the RFCs to better understand the interactions but all I could find is that 1.3 obsoletes 5077, which doesn't quite make it clear what we should do here.

Nonetheless, I hope this is still a usable fix and a test case for the most egregious problem.

**Comment by djc** [comment]
Apart from fixing the original issue, the third commit here fixes another issue where we don't filter the `resuming_session` based on whether it matches the presently negotiated version, which could lead to strange effects (added test to make sure we don't add a TLS 1.3 cache entry when resuming to 1.2). Will create another PR for deeper refactoring changes.
