### PR TITLE
Return correct `ConnectionTrafficSecrets` variant when AES-256-GCM is negotiated.

### LINKED ISSUE #1833: Connection::dangerous_extract_secrets returns ConnectionTrafficSecrets::Aes128Gcm even when AES-256-GCM is negotiated
**Checklist**
* [x] I've searched the issue tracker for similar bugs.

**Describe the bug**
With the ring provider, when a connection is negotiated with TLS 1.2 and ciphersuite using AES-256-GCM, `conn.dangerous_extract_secrets()` should return `tx` and `rx` that contain `ConnectionTrafficSecrets::Aes256Gcm { ... }`. Instead they contain `ConnectionTrafficSecrets::Aes128Gcm { ... }` (with the correct 32-bit `AeadKey`).

Bug is at https://github.com/rustls/rustls/blob/546a85d91277a1009d199aa1e2829ecf153e2631/rustls/src/crypto/ring/tls12.rs#L165

... introduced in 0.22 with [the switch to the `AeadKey` type.](https://github.com/rustls/rustls/commit/55bb27953d52eb2762f20aa6e30dc54252b1f77e#diff-8937aaa993339f2719b41809ab51f79f4e6f04de326cde3e3fda1e813a5ef693R155)

**To Reproduce**

```toml
rustls = { version = "0.23", features = ["ring"] }
webpki-roots = "0.26"
```

```rust
fn main() {
    use rustls::{ClientConfig, ClientConnection, ConnectionTrafficSecrets, ExtractedSecrets, RootCertStore, Stream, crypto::{ring as rustls_ring, CryptoProvider}};

    let hostname = "www.google.com";

    let cipher_suites = vec![
        rustls_ring::cipher_suite::TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
        rustls_ring::cipher_suite::TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
    ];

    let crypto_provider = CryptoProvider {
        cipher_suites,
        ..rustls_ring::default_provider()
    };
    crypto_provider.install_default().unwrap();

    let root_store = RootCertStore {
        roots: webpki_roots::TLS_SERVER_ROOTS.to_owned(),
    };

    let mut config =
        ClientConfig::builder_with_protocol_versions(&[&rustls::version::TLS12])
        .with_root_certificates(root_store)
        .with_no_client_auth();
    config.enable_secret_extraction = true;
    let config = std::sync::Arc::new(config);

    let name = hostname.try_into().unwrap();

    let mut conn = ClientConnection::new(config, name).unwrap();
    let mut sock = std::net::TcpStream::connect("www.google.com:443").unwrap();
    let mut tls = Stream::new(&mut conn, &mut sock);
    std::io::Write::write_all(&mut tls, b"\r\n").unwrap();
    let protocol_version = conn.protocol_version().unwrap();
    println!(
        "using {protocol_version:?} {:?}",
        conn.negotiated_cipher_suite(),
    );
    let ExtractedSecrets { tx, rx } = conn.dangerous_extract_secrets().unwrap();
    match tx.1 {
        ConnectionTrafficSecrets::Aes256Gcm { key, .. } => {
            assert_eq!(key.as_ref().len(), 32);
            println!("tx is ConnectionTrafficSecrets::Aes256Gcm with key {:?}B key", key.as_ref().len());
        },

        ConnectionTrafficSecrets::Aes128Gcm { key, .. } => panic!("tx is ConnectionTrafficSecrets::Aes128Gcm with key {:?}B key", key.as_ref().len()),

        ConnectionTrafficSecrets::Chacha20Poly1305 { key, .. } => panic!("tx is ConnectionTrafficSecrets::Chacha20Poly1305 with key {:?}B key", key.as_ref().len()),

        _ => unreachable!(),
    }
    match rx.1 {
        ConnectionTrafficSecrets::Aes256Gcm { key, .. } => {
            assert_eq!(key.as_ref().len(), 32);
            println!("rx is ConnectionTrafficSecrets::Aes256Gcm with key {:?}B key", key.as_ref().len());
        },

        ConnectionTrafficSecrets::Aes128Gcm { key, .. } => panic!("rx is ConnectionTrafficSecrets::Aes128Gcm with key {:?}B key", key.as_ref().len()),

        ConnectionTrafficSecrets::Chacha20Poly1305 { key, .. } => panic!("rx is ConnectionTrafficSecrets::Chacha20Poly1305 with key {:?}B key", key.as_ref().len()),

        _ => unreachable!(),
    }
}
```

Expected:

```
using TLSv1_2 Some(TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384)
tx is ConnectionTrafficSecrets::Aes256Gcm with key 32B key
rx is ConnectionTrafficSecrets::Aes256Gcm with key 32B key
```

Actual:

```
using TLSv1_2 Some(TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384)
thread 'main' panicked at src/main.rs:46:60:
tx is ConnectionTrafficSecrets::Aes128Gcm with key 32B key
```

**Applicable Version(s)**
rustls v0.23.1

**Expected behavior**
Explained above.

**Additional context**
Workaround is to ignore the enum type and branch on `key.as_ref().len()`

### PR DESCRIPTION
**Pull request by Arnavion**
55bb27953d52eb2762f20aa6e30dc54252b1f77e inadvertently changed `extract_keys` to always return `ConnectionTrafficSecrets::Aes128Gcm`, even when AES-256-GCM was negotiated. This change fixes it by restoring the key length check.

Fixes #1833

### CODE REVIEW

**Comment by Arnavion** [comment]
I didn't add a test for this because the existing tests don't test with the granularity of specific protocol versions / ciphersuites. I can add a test if you want, though in that case I would rather add something that exhaustively tests every combination of TLS 1.2 / TLS 1.3 and AES-128-GCM / AES-256-GCM / CHACHA20-POLY1305.

In fact I hit the original bug with a kTLS client that tests every combination in exactly that way. I *have* verified this branch using that client.

**Comment by ctz** [comment]
Thanks for the report and the fix! Going to go ahead and push a test for this on top of your PR -- I expect this will point to a similar problem in the aws-lc-rs code.

**Review by cpu — APPROVED** [review]
🤦‍♂️ thanks for catching my mistake here!

File: rustls/src/crypto/ring/tls12.rs [hunk 1]
```diff
@@ -162,9 +162,16 @@ impl Tls12AeadAlgorithm for GcmAlgorithm {
         write_iv: &[u8],
         explicit: &[u8],
     ) -> Result<ConnectionTrafficSecrets, UnsupportedOperationError> {
-        Ok(ConnectionTrafficSecrets::Aes128Gcm {
-            key,
-            iv: gcm_iv(write_iv, explicit),
+        Ok(match self.0.key_len() {
+            16 => ConnectionTrafficSecrets::Aes128Gcm {
+                key,
+                iv: gcm_iv(write_iv, explicit),
```
Comment (djc) [inline rustls/src/crypto/ring/tls12.rs:168]: Nit: would prefer to extract `let iv = gcm_iv(write_iv, explicit);`.

**Review by djc — APPROVED** [review]

File: rustls/src/crypto/ring/tls12.rs (hunk 1 above)
Comment (Arnavion) [reply rustls/src/crypto/ring/tls12.rs]: Done.

**Review by ctz — APPROVED** [review]

**Comment by ctz** [comment]
Thank you!

**Comment by djc** [comment]
I guess we should do a release for this?

**Comment by ctz** [comment]
Certainly, yes. I'll aim to cut a 0.23.2 later this week.
