### PR TITLE
Fix `complete_io()` for non-blocking IO

### LINKED ISSUE #2584: 0.23.30 appears to stall my integration tests on WSL2
**Checklist**
* [x] I've searched the issue tracker for similar bugs.

**Describe the bug**
My integration tests which make requests consistently stall out with maxed CPU on rustls version 0.23.30 when running on WSL2.

**To Reproduce**
1. Run `cargo test` on WSL2

**Applicable Version(s)**
0.23.30

**Expected behavior**
The tests run without incident.

**Additional context**
Locking rustls to version 0.23.29 resolves the issue for now.

Version 0.23.30 works without incident on my Mac.

My app continues to run normally via `cargo run` on WSL2.

My WSL2 is running Debian 12.11.

It stalls in both the VSCode terminal and in Windows Terminal.

A sample test which stalls:
```rust
/// Tests the login form page rendering.
#[tokio::test]
async fn login_form() -> Result<(), Box<dyn Error + Send + Sync>> {
    let (router, _state) = init_test().await;
    let request = Request::builder()
        .uri("/login")
        .header(X_REAL_IP, TEST_IP)
        .body(Body::empty())?;
    let response = router.oneshot(request).await?;

    assert!(response.status().is_success());
    let body_str = response_body_str(response).await;
    assert!(body_str.contains("Log in"));
    Ok(())
}
```

### PR DESCRIPTION
**Pull request by ctz**
fixes #2584 re #2559 re #2556

This introduces improved testing of `complete_io()` (tests which demonstrate the lack of progress bug reported in #2584) and then fixes it in two ways. It also fixes a case where the original issue would return `(0, 0)` rather than the desired error.

I don't much like `complete_io()`; it is doing way too much. But this PR is intended to apply cleanly onto rel-0.23, so I'll leave more significant changes to later.

### CODE REVIEW

File: rustls-test/src/lib.rs [hunk 1]
```diff
@@ -985,6 +985,66 @@ impl io::Read for FailsReads {
     }
 }
 
+/// An object that impls Read and Write and raises WouldBlock a lot.
+///
+/// This object panics on drop if the configured expected reads/writes
+/// didn't take place.
+#[derive(Debug, Default)]
+pub struct NonBlockError {
```
Comment (cpu) [inline rustls-test/src/lib.rs]: bikeshedding, but it doesn't seem like this struct name maps well to the documentation of how it works. Maybe better named something like `MockInputOutput` or `AccountingIO`?

Similarly, I think the headline comment might be improved if the `WouldBlock` part was the second line:

```
/// An object that impls `io::Read` and `io::Write` by deferring operations to member `Vec`s
///
/// Returns `WouldBock` if an operation doesn't have a corresponding `Vec` entry.
///
/// This object panics on drop if the configured expected reads/writes
/// didn't take place.

File: rustls-test/src/lib.rs [hunk 2]
```diff
@@ -985,6 +985,66 @@ impl io::Read for FailsReads {
...
+        println!("flush");
+        Ok(())
+    }
+}
+
+impl Drop for NonBlockError {
+    fn drop(&mut self) {
+        // ensure the object was exhausted as expected
+        assert_eq!(self.reads.as_slice(), Vec::<Vec<u8>>::new());
+        assert_eq!(self.writes.as_slice(), Vec::<usize>::new());
```
Comment (cpu) [inline rustls-test/src/lib.rs]: am I missing a detail, or could these be simplified with `is_empty()`? Like `assert!(self.reads.is_empty())` and `assert!(self.writes.is_empty())`

File: rustls/src/conn.rs [hunk 3]
```diff
@@ -603,6 +603,15 @@ impl<Data> ConnectionCommon<Data> {
                 return Ok((rdlen, wrlen));
             }
 
+            // If we want to write, but are WouldBlocked by the underlying IO, *and*
+            // have no desire to read; that is everything.
+            if let (Some(_), false) = (&blocked_write, self.wants_read()) {
+                return match wrlen {
+                    0 => Err(blocked_write.unwrap()),
```
Comment (cpu) [inline rustls/src/conn.rs:610]: I spent a bit of time twisting this code (and the equiv in the read path) to try and avoid the option `unwrap()` but couldn't come up with anything. This seems like the best diff for the current impl.

**Review by cpu — APPROVED** [review]
> This function is complex because it does too much (we should fix that)

I concur :sweat:

File: rustls-test/src/lib.rs (hunk 2 above)
Comment (ctz) [reply rustls-test/src/lib.rs]: This is an attempt to produce a good error on assertion failure. But probably not worth the extra noise.

Comment (cpu) [reply rustls-test/src/lib.rs]: Ahhhh, that makes sense. I don't feel strongly, but maybe worth a comment since it wasn't super obvious.

File: rustls-test/src/lib.rs (hunk 1 above)
Comment (ctz) [reply rustls-test/src/lib.rs]: -> `TestNonBlockIo` and reworded the doc comment
